listenAddress: ":8880"
tls: true
gzip: true
certFile: fullchain.pem
keyFile: privkey.pem
hostMap:
  www.cubex-local.com:  "8888"
  live.cubex-local.com:  "https://www.cubex.io"
  "fortifi.*\\.cubex\\-local\\.com":  "9090"
