listenAddress: ":8880"
gzip: true
tls: true
certFile: fullchain.pem
keyFile: privkey.pem
streaming: true
tunnelName: # publishes https://<name>.cubex.cloud and https://*.<name>.cubex.cloud
hostMap:
  www.cubex-local.com: "8888"
  live.cubex-local.com: "https://www.cubex.io"
  "fortifi.*\\.cubex\\-local\\.com": "9090"
